### ISSUE TITLE
E number bug

### ISSUE THREAD

**Issue by SG4-Yaris** [tildejustin/planifolia#4]
with
![with](https://github.com/tildejustin/planifolia/assets/147867939/55029c2e-1079-4d19-9742-39a3734078ee)
without
![without](https://github.com/tildejustin/planifolia/assets/147867939/05ac6a56-0ca0-4fcb-8e38-76cd80e14027)
With planifolia the E number always shows: -1/all entities
instead of: entities on screen/all entities

I use all mods from the allowed list except krypton in version 1.17.1

**Comment by tildejustin** [comment]
this is very intentional and has been a staple of 1.16.1 sodium for years (https://github.com/Minecraft-Java-Edition-Speedrunning/sodium/commit/5a1b3767c3601bd79b5b0d4fa857781507e73e2f); it only does this when entity culling is on. With entity culling on, the behavior of e-ray is  different, and since it's not like vanilla, it is disabled.

**Comment by SG4-Yaris** [comment]
So I just turn on entity culling and then it works?
Oh and how do I do that?
I dont need it for runs just thought it was a bug or something as it didn't seem intentional

**Comment by tildejustin** [comment]
a toggle for entity culling is available in the sodium options on the title screen, added to the vanilla menu at the bottom when in a world, and standardsettings has the ability to modify it as well.

**Comment by SG4-Yaris** [comment]
Ok thanks a lot
